# Generated by Django 5.1.4 on 2025-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_department_studentid_recipe_recipe_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.TextField(default=100),
        ),
    ]
