# Generated by Django 5.1.4 on 2025-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_student_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date_of_established',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
