# Generated by Django 5.1.4 on 2025-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_recipe_is_deleted_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
